image: node:latest

stages:
  - test and build
  - deploy

before_script:
  - npm install

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

jest:
  stage: test and build
  script:
    - npm run test
  artifacts:
    paths:
      - test-report.xml
    reports:
      junit: test-report.xml

tslint:
  stage: test and build
  script:
    - npm run tslint

prettier:
  stage: test and build
  script:
    - npm run prettier

tsc:
  stage: test and build
  script:
    - npm run build
  artifacts:
    paths:
      - build/

production:
  stage: deploy
  before_script:
    - npm config set prefix /usr/local
    - npm install -g serverless
  script:
    - serverless deploy --stage production --verbose --iftttKeysJsonArray "$IFTTT_KEY_JSON_ARRAY"
  environment: production
  only:
    refs:
      - master
