service: snow-day-notifier
provider:
  name: aws
  runtime: nodejs10.x

functions:
  checkForDelays:
    handler: build/index.checkForDelays
    events:
      - http: POST checkForDelays
      - schedule: rate(5 minutes)
    environment:
      IFTTT_KEYS: ${opt:iftttKeysJsonArray}
      AWS_DYNAMO_REGION: ${opt:awsDynamoRegion}

resources:
  Resources:
    snowDayNotifierTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: snowDayNotifierTable
        AttributeDefinitions:
          - AttributeName: key
            AttributeType: S
        KeySchema:
          - AttributeName: key
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
