service: snow-day-notifier
provider:
  name: aws
  runtime: nodejs10.x

functions:
  checkForDelays:
    handler: build/index.checkForDelays
    events:
      - http: POST checkForDelays
      - schedule: rate(5 minutes)
    environment:
      IFTTT_KEYS: ${opt:iftttKeysJsonArray}
