service: snow-day-notifier
provider:
  name: aws
  runtime: nodejs10.x
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: 'arn:aws:dynamodb:us-east-1:*:*'

functions:
  checkForDelays:
    handler: build/index.checkForDelays
    events:
      - http: POST checkForDelays
      - schedule: rate(5 minutes)
    environment:
      IFTTT_KEYS: ${opt:iftttKeysJsonArray}
      AWS_DYNAMO_REGION: ${opt:awsDynamoRegion}

resources:
  Resources:
    snowDayNotifierTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: snowDayNotifierTable
        AttributeDefinitions:
          - AttributeName: CONFIG_KEY
            AttributeType: S
        KeySchema:
          - AttributeName: CONFIG_KEY
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
